### ISSUE TITLE
cannot install elffile

### ISSUE THREAD

**Issue by skxo** [jsandin/esp-bin2elf#6]
Hello,

using pip I cannot install elffile.

pip install elffile -i https://pypi.python.org/simple/

....
 urllib2.HTTPError: HTTP Error 403: SSL is required
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-E9hCtO/elffile/

If someone can help me, it would be really cool.
Thanks!

**Comment by ururk** [comment]
While it isn't the best workaround, you can get it to install by doing the following:

Download the source for elffile

Extract the files

Modify `distribute_setup.py` - change `http://pypi.python.org...` to `https://pypi.python.org...`

Additionally, I had to manually `pip install sphinx` before continuing.

`pip install elffile_directory`

**Comment by zayfod** [comment]
The original elffile project seems abandoned, but I found the following fork: https://github.com/slorquet/elffile2

It can be installed from source like this:

```
git clone https://github.com/slorquet/elffile2.git
cd elffile2
python setup.py install
```

**Comment by ghost** [comment]
elffile2 fails, 

```
voltagex@debian:~/src/elffile2$ sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    import elffile
  File "/home/voltagex/src/elffile2/elffile.py", line 36, in <module>
    import coding
ImportError: No module named coding
```

**Comment by CarlosGS** [comment]
Downloaded "coding" from here https://pypi.org/project/coding/#files
And copied the coding.py file to the script directory

https://xkcd.com/2347/
