### ISSUE TITLE
esp_elf.py spell error: section_address->section_adddress

### ISSUE THREAD

**Issue by Zepan** [jsandin/esp-bin2elf#7]
esp_elf.py  line121: section_address->section_adddress
case error

**Comment by zayfod** [comment]
Fixed here: https://github.com/zayfod/esp-bin2elf

**Comment by aldock** [comment]
Hi zayfod,

It worked with python2 but with section addres error.
After your changes, works with python3 and i did the alternation from python2 to 3, all modules reinstalled again, elffile2..., found right path with os.getcwd(), running again.
Again all ok...  "except again section addres error"  last commmand, now line 122:

elf = esp_bin2elf.convert_rom_to_elf(rom, section_names, 'flash_bin.elf')
Traceback (most recent call last):
File "", line 1, in
File "/home/osboxes/Desktop/esp_bin2elf.py", line 48, in convert_rom_to_elf
elf_section = ElfSection(name, section.address, section.contents)
File "/home/osboxes/Desktop/esp_elf.py", line 122, in init
raise Exception("Can't find settings for 0x%08x" % section_address)
Exception: Can't find settings for 0x40200000

Hope you can help.

**Comment by aldock** [comment]
Found a way, got directly from Arduino build :).  Super easy.
